### ISSUE TITLE
RuntimeException: error loading page

### ISSUE THREAD

**Issue by carstenbaumhoegger** [JoanZapata/android-pdfview#115]
I can't open a downloaded PDF on a Galaxy S3 Mini.
It always causes the following exception:

`java.lang.RuntimeException: error loading page
at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
at org.vudroid.core.DecodeServiceBase.getPageWidth(DecodeServiceBase.java:214)
at com.joanzapata.pdfview.PDFView.loadComplete(PDFView.java:647)
at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:58)
at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:31)
at android.os.AsyncTask.finish(AsyncTask.java:631)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4867)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
at dalvik.system.NativeStart.main(Native Method)`

I can't reproduce this error on my HTC One M8, I don't know how to fix it, but it seems that there's an error in your library.
Would be nice if you can fix it! :)

**Comment by JoanZapata** [comment]
It might be related to #82, can you try using the latest version of PDFView from master?

**Comment by carstenbaumhoegger** [comment]
Sure, how do I use the latest master version instead of 1.0.3?

**Comment by JoanZapata** [comment]
Are you using maven or gradle ?

**Comment by carstenbaumhoegger** [comment]
Gradle

**Comment by JoanZapata** [comment]
I just published the latest version `1.0.4` on maven central. You should be able to test it in a few hours by increasing the version you're using.

**Comment by carstenbaumhoegger** [comment]
alright, I used the 1.0.4 and now I get another error on the S3 Mini
`java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.RuntimeException: PDF file is corrupted
at org.vudroid.pdfdroid.codec.PdfDocument.open(Native Method)
at org.vudroid.pdfdroid.codec.PdfDocument.openDocument(PdfDocument.java:28)
at org.vudroid.pdfdroid.codec.PdfContext.openDocument(PdfContext.java:18)
at org.vudroid.core.DecodeServiceBase.open(DecodeServiceBase.java:59)
at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:52)
at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:31)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
... 4 more`

**Comment by JoanZapata** [comment]
This error is related to the underlying library not being able to read the PDF file. There's not so much I can do, but an issue is opened to be able to catch this exception and warn the user in #29. I'm closing this one now.

**Comment by derohimat** [comment]
i always found this after load page 16 and want load page 17

**Comment by mengxiaojie** [comment]
02-22 18:33:15.189 28979-28979/com.ys100.listpdf E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.ys100.listpdf, PID: 28979
                                                                   java.lang.RuntimeException: error loading page
                                                                       at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
                                                                       at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
                                                                       at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
                                                                       at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
                                                                       at org.vudroid.core.DecodeServiceBase.getPageWidth(DecodeServiceBase.java:214)
                                                                       at com.joanzapata.pdfview.PDFView.loadComplete(PDFView.java:644)
                                                                       at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:58)
                                                                       at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:31)
                                                                       at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                                       at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5601)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)


I meet the same problem, please help me to solve it
