### ISSUE TITLE
error loading page

### ISSUE THREAD

**Issue by bartbergmans** [JoanZapata/android-pdfview#116]
I get the following error when browsing through a pdf:

    E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #5
        Process: eu.shimano.fish, PID: 21507
        java.lang.RuntimeException: An error occured while executing doInBackground()
                at android.os.AsyncTask$3.done(AsyncTask.java:304)
                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at java.lang.Thread.run(Thread.java:818)
         Caused by: java.lang.RuntimeException: error loading page
                at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
                at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
                at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
                at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
                at com.joanzapata.pdfview.RenderingAsyncTask.proceed(RenderingAsyncTask.java:100)
                at com.joanzapata.pdfview.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:63)
                at com.joanzapata.pdfview.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:33)
                at android.os.AsyncTask$2.call(AsyncTask.java:292)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at java.lang.Thread.run(Thread.java:818)

I got the latest version:

    compile 'com.joanzapata.pdfview:android-pdfview:1.0.3@aar'

**Comment by carstenbaumhoegger** [comment]
This issue could be duplicate, the error looks exactly like the one i've reported in #115

**Comment by JoanZapata** [comment]
Please use version 1.0.4.
