### ISSUE TITLE
Minimum andrpoid api level?

### ISSUE THREAD

**Issue by nnttoo** [JoanZapata/android-pdfview#127]
I've tried in gingerbread and does not seem to work? or there is something wrong? what android minimum API level for this library?

**Comment by carstenbaumhoegger** [comment]
minSDK is 8 which represents Android 2.2 Froyo, so Gingerbread should be supported.

**Comment by nnttoo** [comment]
07-06 22:20:43.580: E/AndroidRuntime(334): FATAL EXCEPTION: main
07-06 22:20:43.580: E/AndroidRuntime(334): java.lang.NoSuchFieldError: 
I get an error like this in gingerbread


android.os.AsyncTask.THREAD_POOL_EXECUTOR
07-06 22:20:43.580: E/AndroidRuntime(334): 	at com.joanzapata.pdfview.PDFView.load(PDFView.java:233)
07-06 22:20:43.580: E/AndroidRuntime(334): 	at com.joanzapata.pdfview.PDFView.load(PDFView.java:213)
07-06 22:20:43.580: E/AndroidRuntime(334): 	at com.joanzapata.pdfview.PDFView.access$8(PDFView.java:212)
07-06 22:20:43.580: E/AndroidRuntime(334): 	at com.joanzapata.pdfview.PDFView$Configurator.load(PDFView.java:1067)


how to solve this?

**Comment by nnttoo** [comment]
I tried to edit PDFview.java on line 233 with the following code
```java
       // Start decoding document
        decodingAsyncTask = new DecodingAsyncTask(uri, this);
        
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
        	 decodingAsyncTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);
          } else {
        	  decodingAsyncTask.execute();
          }
       

        renderingAsyncTask = new RenderingAsyncTask(this);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
       	 decodingAsyncTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);
         } else {
       	  decodingAsyncTask.execute();
         }
```
but still force close with logcat:
```PLAIN
07-06 22:42:12.629: E/AndroidRuntime(371): java.lang.NoClassDefFoundError: android.animation.ValueAnimator
07-06 22:42:12.629: E/AndroidRuntime(371): 	at com.joanzapata.pdfview.AnimationManager.startYAnimation(AnimationManager.java:64)
07-06 22:42:12.629: E/AndroidRuntime(371): 	at com.joanzapata.pdfview.PDFView.showPage(PDFView.java:277)
07-06 22:42:12.629: E/AndroidRuntime(371): 	at com.joanzapata.pdfview.PDFView.jumpTo(PDFView.java:256)
07-06 22:42:12.629: E/AndroidRuntime(371): 	at com.joanzapata.pdfview.PDFView.loadComplete(PDFView.java:662)
07-06 22:42:12.629: E/AndroidRuntime(371): 	at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:58)

```

**Comment by willinimmer** [comment]
Same issue here on a Motorola MB632 with Android Version 2.3.6
Any help appreciated, thank you so much!

Fatal Exception: java.lang.NoSuchFieldError
android.os.AsyncTask.THREAD_POOL_EXECUTOR	
com.joanzapata.pdfview.PDFView.load (PDFView.java:233)	
com.joanzapata.pdfview.PDFView.load (PDFView.java:213)	
com.joanzapata.pdfview.PDFView.access$1000 (PDFView.java:64)	
com.joanzapata.pdfview.PDFView$Configurator.load (PDFView.java:1067)

**Comment by nnttoo** [comment]
The library seems to only work on the API level 11 or above

read here: 
https://github.com/JoanZapata/android-pdfview/issues/90

and here:

https://github.com/JoanZapata/android-pdfview/pull/105

**Comment by AhmadullahSaikat** [comment]
Error

11-05 22:52:59.844 2063-2063/com.test.testapplication E/AndroidRuntime: java.lang.NoSuchFieldError: android.os.AsyncTask.THREAD_POOL_EXECUTOR
11-05 22:52:59.844 2063-2063/com.test.testapplication E/AndroidRuntime:     at com.joanzapata.pdfview.PDFView.load(PDFView.java:233)
11-05 22:52:59.844 2063-2063/com.test.testapplication E/AndroidRuntime:     at com.joanzapata.pdfview.PDFView.load(PDFView.java:213)
11-05 22:52:59.844 2063-2063/com.test.testapplication E/AndroidRuntime:     at com.joanzapata.pdfview.PDFView.access$1000(PDFView.java:64)
11-05 22:52:59.844 2063-2063/com.test.testapplication E/AndroidRuntime:     at com.joanzapata.pdfview.PDFView$Configurator.load(PDFView.java:1067)
