### ISSUE TITLE
java.lang.RuntimeException: error loading page

### ISSUE THREAD

**Issue by zhijiazheng123** [JoanZapata/android-pdfview#172]
java.lang.RuntimeException: error loading page
	at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
	at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
	at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
	at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
	at org.vudroid.core.DecodeServiceBase.getPageWidth(DecodeServiceBase.java:214)
	at com.joanzapata.pdfview.PDFView.loadComplete(PDFView.java:644)
	at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:58)
	at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:31)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5336)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by derohimat** [comment]
many problem same with you
and not resolve now

**Comment by derohimat** [comment]
java.lang.RuntimeException: error loading page 
at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
