### ISSUE TITLE
PDF file is corrupted

### ISSUE THREAD

**Issue by geolyth** [JoanZapata/android-pdfview#185]
Hi all,
I have the same issue of others...

```java
FATAL EXCEPTION: AsyncTask #1
    Process: it.creact.findit, PID: 3052
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.RuntimeException: PDF file is corrupted
        at org.vudroid.pdfdroid.codec.PdfDocument.open(Native Method)
        at org.vudroid.pdfdroid.codec.PdfDocument.openDocument(PdfDocument.java:28)
        at org.vudroid.pdfdroid.codec.PdfContext.openDocument(PdfContext.java:18)
        at org.vudroid.core.DecodeServiceBase.open(DecodeServiceBase.java:59)
        at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:52)
        at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:31)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

I also tried to add jniLibs but my continue to crash...
Anyone has ideas on how to fix it?

Thanks in advance,
Fabio

**Comment by pankajkrdos** [comment]
Sick of this issue. 
I have tried for a custom implementation but the error is same.

**Comment by ChubyAvodroc** [comment]
Hi there
I used to have same problem as, let me tell you how i solved it.

To start with I'm using this project as an import module with gradle, like this `compile project(':PDFview')` rather than this `compile 'com.joanzapata.pdfview:android-pdfview:1.0.4@aar'`, in this way i was able to modify the code and catch the exception.

In DecodingAsyncTask class add a try catch like this

```java
@Override
    protected Void doInBackground(Void... params) {
        // HACK: 21/04/16 Add try catch in order to prevent PDF corrupted file
        try {
            decodeService = new DecodeServiceBase(new PdfContext());
            decodeService.setContentResolver(context.getContentResolver());
            decodeService.open(uri);
        } catch (RuntimeException rte) {
            decodeService = null;
            Log.e(TAG, "doInBackground: ", rte);
        }
        return null;
    }
```
And on PDFView class just check for decodeService not null

```java
public void loadComplete(DecodeService decodeService) {
        // HACK: 21/04/16 If decodeService is null then there was a problem with the PDF load
        if (decodeService != null) {
            this.decodeService = decodeService;
            this.documentPageCount = decodeService.getPageCount();

            // We assume all the pages are the same size
            this.pageWidth = decodeService.getPageWidth(0);
            this.pageHeight = decodeService.getPageHeight(0);
            state = State.LOADED;
            calculateOptimalWidthAndHeight();

            // Notify the listener
            jumpTo(defaultPage);
            if (onLoadCompleteListener != null) {
                onLoadCompleteListener.loadComplete(documentPageCount);
            }
        } else {
            jumpTo(defaultPage);
            if (onLoadCompleteListener != null) {
                onLoadCompleteListener.loadComplete(-1);
            }
        }
    }
```

Doing that the problem was solved, at least for my case, Hope it helps you

**Comment by jatin-lakhani** [comment]
+1 having same issue

**Comment by iArsalanshah** [comment]
Thank you @ChubyAvodroc  :+1:
