### ISSUE TITLE
 java.lang.RuntimeException: error loading page

### ISSUE THREAD

**Issue by bineanzhou** [JoanZapata/android-pdfview#199]
java.lang.RuntimeException: error loading page
                                                                                                                             at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
                                                                                                                             at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
                                                                                                                             at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
                                                                                                                             at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
                                                                                                                             at org.vudroid.core.DecodeServiceBase.getPageWidth(DecodeServiceBase.java:214)
                                                                                                                             at com.joanzapata.pdfview.PDFView.loadComplete(PDFView.java:644)
                                                                                                                             at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:58)
                                                                                                                             at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:31)
                                                                                                                             at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                                                                             at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                                                                             at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ArtemMikhaylov** [comment]
I have the same problem. It happens only for some pdf files and works fine for others. Can't figure out what's the difference between them.

**Comment by cike** [comment]
这个问题很突出，不能解决此问题 组件基本不可用，望大神修复一下。

**Comment by yueshao6800** [comment]
The same problean!!!

**Comment by ywlm423** [comment]
大神求解决

**Comment by gaao2017** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.heart.health.consultant, PID: 31921
                                                                             java.lang.RuntimeException: error loading page
                                                                                 at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
                                                                                 at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
                                                                                 at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
                                                                                 at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
                                                                                 at org.vudroid.core.DecodeServiceBase.getPageWidth(DecodeServiceBase.java:214)
                                                                                 at com.joanzapata.pdfview.PDFView.loadComplete(PDFView.java:644)
                                                                                 at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:58)
                                                                                 at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:31)
                                                                                 at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                                 at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                                 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5578)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

Request the author to repair

**Comment by jeromyniu** [comment]
anybody have solved the problem?

**Comment by BinarySatan** [comment]
这库不可用啊，我就加载了一个pdf, 进入翻一页直接 Crash。

**Comment by gj009351** [comment]
I have the same problem.
