### ISSUE TITLE
I meet  a problem when I

### ISSUE THREAD

**Issue by limaoyin** [JoanZapata/android-pdfview#204]
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): An error occured while executing doInBackground()
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): java.lang.RuntimeException: An error occured while executing doInBackground()
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at java.lang.Thread.run(Thread.java:838)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load vudroid from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lmy-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.lmy-1, /vendor/lib, /system/lib]]]: findLibrary returned null
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at java.lang.System.loadLibrary(System.java:514)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at org.vudroid.core.VuDroidLibraryLoader.load(VuDroidLibraryLoader.java:13)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at org.vudroid.pdfdroid.codec.PdfContext.<clinit>(PdfContext.java:13)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:50)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:31)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
05-17 16:53:22.815: A/MobUncaughtExceptionHandler(19898): 	... 3 more
05-17 16:53:22.838: E/AndroidRuntime(19898): FATAL EXCEPTION: AsyncTask #4
05-17 16:53:22.838: E/AndroidRuntime(19898): java.lang.RuntimeException: An error occured while executing doInBackground()
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at java.lang.Thread.run(Thread.java:838)
05-17 16:53:22.838: E/AndroidRuntime(19898): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load vudroid from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lmy-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.lmy-1, /vendor/lib, /system/lib]]]: findLibrary returned null
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at java.lang.System.loadLibrary(System.java:514)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at org.vudroid.core.VuDroidLibraryLoader.load(VuDroidLibraryLoader.java:13)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at org.vudroid.pdfdroid.codec.PdfContext.<clinit>(PdfContext.java:13)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:50)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:31)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
05-17 16:53:22.838: E/AndroidRuntime(19898): 	... 3 more

**Comment by FranciscoBartilotti** [comment]
Did you added the JniLibs to your proyect?
