### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by zhangqilu** [JoanZapata/android-pdfview#240]
java.lang.RuntimeException: error loading page
        at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
        at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
        at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
        at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
        at org.vudroid.core.DecodeServiceBase.getPageWidth(DecodeServiceBase.java:214)
        at com.joanzapata.pdfview.PDFView.loadComplete(PDFView.java:644)
        at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:58)
        at com.joanzapata.pdfview.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:31)
        at android.os.AsyncTask.finish(AsyncTask.java:636)
        at android.os.AsyncTask.access$500(AsyncTask.java:177)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:210)
        at android.app.ActivityThread.main(ActivityThread.java:5809)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by alanforgithub** [comment]
我也有这个问题

**Comment by strivecheng** [comment]
这个库很早就不维护，看readme，作者说了

**Comment by gkblack** [comment]
> 这个库很早就不维护，看readme，作者说了

还有其他pdf库么
