### ISSUE TITLE
Crash on document load 

### ISSUE THREAD

**Issue by mediazard** [JoanZapata/android-pdfview#25]
```
E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: it.programmatica.reader, PID: 4942
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.UnsatisfiedLinkError: Couldn't load vudroid from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/it.programmatica.reader-2.apk"],nativeLibraryDirectories=[/data/app-lib/it.programmatica.reader-2, /vendor/lib, /system/lib]]]: findLibrary returned null
            at java.lang.Runtime.loadLibrary(Runtime.java:358)
            at java.lang.System.loadLibrary(System.java:526)
            at org.vudroid.core.VuDroidLibraryLoader.load(VuDroidLibraryLoader.java:13)
            at org.vudroid.pdfdroid.codec.PdfContext.<clinit>(PdfContext.java:13)
            at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:50)
            at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:31)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

```

thanks

**Comment by Truerall** [comment]
@demonar , Hi,

I have included this lib, using android studio like this:

compile 'com.joanzapata.pdfview:android-pdfview:1.0.2@aar'

and also had such problem as OP.  I can test it using your code with "+" in version, but Im not sure that it will solve the problem. So to solve it, I must copy libs to my projects folder ?

**Comment by GuilhE** [comment]
I'm having this problem and none of the solutions regarding adding dependencies worked.
I'm trying something like:
 task copyNativeLibs(type: Copy) {
        from(new File(project(':app-module').buildDir, 'native-libs')) { include '**/*.so' }
        into new File(buildDir, 'native-libs')
    }

But it's failing too.

**Comment by Zorpix** [comment]
I'm having this issue as well. Compiling via gradle like Demonar suggests doesn't work for me. Copying over lib files doesn't seem to work either. Not really sure what to do here.

**Comment by GuilhE** [comment]
solved by adding jniLibs.srcDirs = [ 'libs' ]:
sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            jniLibs.srcDirs = [ 'libs' ]
            res.srcDirs = ['res']
            java.srcDirs = ['src']
        }
    }

**Comment by montreux** [comment]
I had this problem as well. I thought I had solved it by adding this line to my build.grade:
* `compile 'com.joanzapata.pdfview:android-pdfview:1.+@aar'`

It worked great in the simulator. Then when I installed it on a HUDL 2 it would crash every time with the java.lang.UnsatisfiedLinkError. The problem was that the HUDL 2 is x86_64 and android-pdfview doesn't include an x86_64 version of vudroid.so. That doesn't matter if no other dependencies have x86_64 libraries, as the 32 bit x86 libraries will be used instead. I did have a dependency that had x86_64 libraries, so no version of vudroid.so would be loaded. I could get rid of the other dependency as I wasn't using it anymore, then everything was ok.

A great tool for debugging this is Native Libs Monitor. Install that on your device and it will say what libraries have been loaded and are available in each app.

**Comment by Lee-swifter** [comment]
I had this problem,  but I solved this by adding the `libvudroid.so` into `lib/armeabi` folder.

**Comment by fanatic007** [comment]
Can someone please elaborate ,how exactly can I add libvudroid.so into lib/armeabi. Where is lib/armeabi is located? I've made android-pdfView available into my project by adding following line in the build.gradle file.
`compile 'com.joanzapata.pdfview:android-pdfview:1.0.4@aar'`

For the record, I started getting this problem after I added some new dependencies  for gcm push services ( gcm.jar, com.google.android.gms:play-services:8.3.0 ). The problem could be because of these new dependencies as montreux mentioned. But as these dependencies are crucial for me, I cannot remove. them.
