### ISSUE TITLE
Application crashes Open "Incomplete PDF"

### ISSUE THREAD

**Issue by nitinmishra27** [JoanZapata/android-pdfview#29]
Hi i ran into problem, when i try to open a pdf which is remaining some part downloaded, the application crashes 

`02-18 14:58:52.749: E/AndroidRuntime(32014): FATAL EXCEPTION: AsyncTask #3
02-18 14:58:52.749: E/AndroidRuntime(32014): Process: com.sfworx.droids.it_ebooks, PID: 32014
02-18 14:58:52.749: E/AndroidRuntime(32014): java.lang.RuntimeException: An error occured while executing doInBackground()
02-18 14:58:52.749: E/AndroidRuntime(32014):    at android.os.AsyncTask$3.done(AsyncTask.java:300)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at java.lang.Thread.run(Thread.java:841)
02-18 14:58:52.749: E/AndroidRuntime(32014): Caused by: java.lang.RuntimeException: PDF file is corrupted
02-18 14:58:52.749: E/AndroidRuntime(32014):    at org.vudroid.pdfdroid.codec.PdfDocument.open(Native Method)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at org.vudroid.pdfdroid.codec.PdfDocument.openDocument(PdfDocument.java:28)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at org.vudroid.pdfdroid.codec.PdfContext.openDocument(PdfContext.java:18)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at org.vudroid.core.DecodeServiceBase.open(DecodeServiceBase.java:59)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:49)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:1)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-18 14:58:52.749: E/AndroidRuntime(32014):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-18 14:58:52.749: E/AndroidRuntime(32014):    ... 3 more`

**Comment by ajaskevics** [comment]
still not solved?

**Comment by JoanZapata** [comment]
PR is still welcome.

**Comment by ajaskevics** [comment]
public relations? ) why don't you just catch the exception and create a callback interface for the developer to catch the error?

**Comment by JoanZapata** [comment]
> public relations?

[Pull Request](https://help.github.com/articles/using-pull-requests/)

> why don't you just catch the exception and create a callback interface for the developer to catch the error?

Because I don't have the time or the need to do so. This library is free and open source, everyone can participate and submit code to be integrated.

**Comment by campiador** [comment]
@JoanZapata Same problem here, would be great if you could kindly make time to fix it.

**Comment by sush4042** [comment]
@JoanZapata , The RenderingAsyncTask.java create the new thread for data render, the exception occur on different thread while load the page on PDFview, It should not allow to manage exception in application. Please can you check this over the service thread execution.

**Comment by milandhanani** [comment]
I added a new update on my brach that might fix this issue. I added a onErrorOCcuredListener class which notifies the parent activity/class when an error occurs while opening a corrupted pdf. I was having the exact same problem and this seems to overcome that. 

Hope it helps. Cheers.

**Comment by Zorpix** [comment]
Since when is fixing crashing when losing internet connection an "enhancement"? This should be a bug. Currently trying to find a workaround. @milandhanani would you be able to make your solution a pull request so the author will acknowledge it?

**Comment by liugt34** [comment]
i meet the problem to,had you solve it ?

**Comment by derohimat** [comment]
@milandhanani : please, publish your branch for fix this problem

**Comment by windydang26** [comment]
02/01/2018 and still not resolve? :(

**Comment by thuongtranhuy** [comment]
Hi,
is this problem resolve?

**Comment by toshihirooya** [comment]
Hi !
is this problem still not resolve... :(

by the way, what is "Incomplete PDF" ???
