### ISSUE TITLE
How to open password protected pdf?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [JoanZapata/android-pdfview#97]
Hi. I want to show password protected pdf to the user, does android-pdfview show opening password protected pdf? If yes what are the methods to input username and password? If no, will you add support in future?

When i tried to open a password protected PDF it crash and the log generated is:

20 15:16:26.324    3776-3798/com.robertlee.pdfdistributor E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #4
    Process: com.robertlee.pdfdistributor, PID: 3776
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.RuntimeException: PDF needs a password!
            at org.vudroid.pdfdroid.codec.PdfDocument.open(Native Method)
            at org.vudroid.pdfdroid.codec.PdfDocument.openDocument(PdfDocument.java:28)
            at org.vudroid.pdfdroid.codec.PdfContext.openDocument(PdfContext.java:18)
            at org.vudroid.core.DecodeServiceBase.open(DecodeServiceBase.java:59)
            at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:52)
            at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:31)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
Thanks.

**Comment by JoanZapata** [comment]
The [underlying rendering library](https://code.google.com/p/vudroid/) doesn't support it, so `PDFView` can't support it.
